[package]
name = "shori"
version = "0.0.4"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pas2rust/shori"
readme = "README.md"
exclude = [
    "tests/*",
    "tests",
    "main.rs"
]
categories = ["cryptography", "security"]
description = "Cryptography utilities and implementations including Argon2, bcrypt, post-quantum algorithms and JWT support"
keywords = ["cryptography", "argon2", "bcrypt", "post-quantum", "jwt"]
authors = ["pas2rust <pas2000@proton.me>"]
homepage = "https://github.com/pas2rust/shori"
documentation = "https://docs.rs/shori"
